# Generated by Django 2.2.7 on 2019-12-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hacksathon',
        ),
    ]
