# Generated by Django 2.2.7 on 2019-12-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_points',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
