# Generated by Django 2.2.7 on 2019-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0002_hackathon_hackathon_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_location_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_location_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
