# Generated by Django 2.2.7 on 2019-12-06 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_users', '0015_team_team_points'),
        ('hackathontime_main', '0003_auto_20191205_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_going',
            field=models.ManyToManyField(to='hackathontime_users.Team'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
