# Generated by Django 2.2.7 on 2019-12-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0004_auto_20191206_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='hackathon_going',
            new_name='hackathon_team_going',
        ),
    ]
