# Generated by Django 2.2.7 on 2019-12-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0005_auto_20191203_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
