# Generated by Django 2.2.7 on 2019-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0005_auto_20191206_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_team_going',
            field=models.ManyToManyField(blank=True, to='hackathontime_users.Team'),
        ),
    ]
