# Generated by Django 2.2.7 on 2019-12-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0006_auto_20191210_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_slug',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_name',
            field=models.CharField(max_length=255),
        ),
    ]
