# Generated by Django 2.2.7 on 2019-12-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_past',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hackthon_future',
            field=models.BooleanField(default=True),
        ),
    ]
