# Generated by Django 2.2.7 on 2019-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0007_auto_20191204_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_period',
            field=models.IntegerField(default=24),
        ),
    ]
