# Generated by Django 2.2.7 on 2019-12-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0008_hackathon_hackathon_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='hackthon_future',
            new_name='hackathon_future',
        ),
    ]
