# Generated by Django 2.2.7 on 2019-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0009_auto_20191210_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='hackathon_address',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='hackathon_geolocation',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_location_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_location_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
