# Generated by Django 2.2.7 on 2019-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0010_auto_20191210_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_location_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_location_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
