# Generated by Django 2.2.7 on 2019-12-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_main', '0012_auto_20191210_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_location_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
