# Generated by Django 2.2.7 on 2019-12-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_users', '0003_auto_20191203_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
