# Generated by Django 2.2.7 on 2019-12-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathontime_users', '0004_auto_20191205_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_in_a_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(to='hackathontime_users.Profile'),
        ),
    ]
