# Generated by Django 2.2.7 on 2019-12-02 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon_Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=100)),
                ('hackathon_content', models.TextField()),
                ('hackathon_date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('hackathon_date', models.DateTimeField()),
                ('hackathon_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
